# Generated by Django 4.0.4 on 2022-11-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=100)),
                ('email_from', models.EmailField(max_length=100)),
                ('email_sub', models.CharField(max_length=100)),
                ('email_body', models.CharField(max_length=100)),
                ('email_attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
